<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <NoWarn>$(NoWarn);TUnit0014;TUnitAssertions0005</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" Version="0.19.74" />
    </ItemGroup>
    
    <ItemGroup>
        <Using Include="TUnit" />
        <Using Include="TUnit.Core.Executors" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Frank.Wpf.Controls.CompletionPopup\Frank.Wpf.Controls.CompletionPopup.csproj" />
      <ProjectReference Include="..\Frank.Wpf.Controls.CSharpRenderer\Frank.Wpf.Controls.CSharpRenderer.csproj" />
      <ProjectReference Include="..\Frank.Wpf.Controls.JsonRenderer\Frank.Wpf.Controls.JsonRenderer.csproj" />
      <ProjectReference Include="..\Frank.Wpf.Controls.VarDump\Frank.Wpf.Controls.VarDump.csproj" />
      <ProjectReference Include="..\Frank.Wpf.Tests.App\Frank.Wpf.Tests.App.csproj" />
    </ItemGroup>

</Project>
